Remove Jdita seriallizer and create `jditaToAst`
evolvedbinary/lwdita pull request #240
Opened 2024-07-24 20:49 UTC by marmoure

This PR removes the tempfix from #172 and completes the round trip xdita -> ast -> jdita -> ast -> xdita

2024-08-01 12:01 UTC, plutonik-a requested changes
Thank you @marmoure, the serialization works as expected!
I have only made some minor suggestions for improvement.

2024-08-06 15:09 UTC, marmoure commented on packages/lwdita-xdita/test/converter.spec.ts
> +describe('JditaToAst', () => {
The name `jditToAst` is consistent with the rest of the file, am I missing something?

2024-08-06 15:10 UTC, marmoure commented on packages/lwdita-xdita/test/converter.spec.ts
> +      "attributes": {},
@plutonik-a Time limitation unfortunately. but it will be tested in the new PR related to full round trip test.

2024-08-06 15:46 UTC, marmoure commented on packages/lwdita-xdita/src/converter.ts
> +
Fixed in [81d75b7](https://github.com/evolvedbinary/lwdita/pull/240/commits/81d75b76cb33f6497b5f7691415dbccf716ca584)

2024-08-06 15:46 UTC, marmoure commented on packages/lwdita-xdita/src/converter.ts
> +  if(jdita.nodeName === 'cdata') {
Added in [81d75b7](https://github.com/evolvedbinary/lwdita/pull/240/commits/81d75b76cb33f6497b5f7691415dbccf716ca584)

2024-08-06 15:46 UTC, marmoure commented on packages/lwdita-xdita/src/converter.ts
> + * convert JDita attributes to Saxes attributes
Fixed in [81d75b7](https://github.com/evolvedbinary/lwdita/pull/240/commits/81d75b76cb33f6497b5f7691415dbccf716ca584)

2024-08-07 09:43 UTC, merged