Prevent Adding significant whitespace in the serializer
evolvedbinary/lwdita pull request #296
Opened 2024-10-21 20:13 UTC by marmoure

Enhance the existent serializer and prevent it from adding significant white-space.

2024-10-22 13:28 UTC, adamretter requested changes

2024-10-22 13:28 UTC, adamretter commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const declaration = `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">\n`;
This should not encode the `\n` here - instead we should be making calls like:
```typescript
const xmlDeclaration = `<?xml version="1.0" encoding="UTF-8"?>`;
const docTypeDeclaraion = `<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">`;

this.outputStream.emit(xmlDeclaration);
this.outputStream.emit(this.EOL);
this.outputStream.emit(docTypeDeclaration);
this.outputStream.emit(this.EOL);

```

2024-10-23 08:24 UTC, marmoure commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const declaration = `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">\n`;
Fixed in [ecac562](https://github.com/evolvedbinary/lwdita/pull/296/commits/ecac5624392674a9f684c48826a32bbce0ba1bb3)

2024-10-23 14:43 UTC, plutonik-a requested changes
@marmoure 
I have added a fix for some comment headers https://github.com/evolvedbinary/lwdita/pull/296/commits/88b08948daf73c71b944b153fb728e95d5e2093d and an update for the relevant README sections (7a494de), and can confirm, that this PR fixes all white-space tests in branch https://github.com/evolvedbinary/lwdita/tree/test/white-sapce. 

However, this PR introduces duplicating the `DOCTYPE` and the XML declaration in the transformed file `./out/output.xml` when running `yarn example`.  It seems both parts are injected on top of the existing parts of the XML document. 

Additionally, when running option 4 (Advanced serialization method) in `packages/lwdita-xdita/example.ts` the required imports are not correctly resolved and break the transformation.

2024-10-23 14:43 UTC, plutonik-a commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const docTypeDeclaration = `<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">`;
@marmoure DOCTYPE and XML declaration are now duplicated in the transformed file `./out/output.xml` when running `yarn example`.

2024-10-24 08:52 UTC, adamretter requested changes

2024-10-24 08:52 UTC, adamretter commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const textTestNode = new TextNode("");
Let's not create a new object each time. I think it would also be better to add a function to node where this check is done. e.g. `node.allowsMixedContent()` that returns true or false.

2024-10-24 08:52 UTC, adamretter commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const textTestNode = new TextNode("");
Refactor as per my comment above please.

2024-10-24 09:36 UTC, marmoure commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const docTypeDeclaration = `<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">`;
Fixed in 0db4153583ac0800390aabcb0f10a1cbe608e901

2024-10-24 09:37 UTC, marmoure commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const textTestNode = new TextNode("");
Fixed in bcc3b5bbc90b0dcf514905a73b9edb3517274ae2

2024-10-24 09:37 UTC, marmoure commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const textTestNode = new TextNode("");
Fixed in bcc3b5bbc90b0dcf514905a73b9edb3517274ae2

2024-10-24 10:00 UTC, plutonik-a commented on packages/lwdita-xdita/src/xdita-serializer.ts
> +    const docTypeDeclaration = `<!DOCTYPE topic PUBLIC "-//OASIS//DTD LIGHTWEIGHT DITA Topic//EN" "lw-topic.dtd">`;
Can confirm that the fix removes the duplicate header now.

2024-10-24 15:11 UTC, merged